#!/usr/bin/env sh

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# global settings
yabai -m config mouse_follows_focus on
yabai -m config focus_follows_mouse autoraise
yabai -m config window_placement second_child
yabai -m config window_topmost off
yabai -m config window_shadow float
yabai -m config window_border off
# yabai -m config window_border_width 2
# yabai -m config active_window_border_color 0xffffff00
# yabai -m config normal_window_border_color 0xff505050
# yabai -m config insert_window_border_color 0xffd75f5f
yabai -m config window_opacity off
yabai -m config active_window_opacity 1.0
yabai -m config normal_window_opacity 0.98
yabai -m config split_ratio 0.50
yabai -m config auto_balance off
yabai -m config mouse_modifier ctrl
yabai -m config mouse_action1 move
yabai -m config mouse_action2 resize
yabai -m config window_border_blur off
yabai -m window_animation_duration 1.0
yabai -m window_animation_frame_rate 60

# general space settings
yabai -m config layout bsp
yabai -m config top_padding 8
yabai -m config bottom_padding 8
yabai -m config left_padding 8
yabai -m config right_padding 8
yabai -m config window_gap 8

# Specific window rules
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Epson Printer Utility 4$" manage=off
yabai -m rule --add app="^Reminders$" manage=off
yabai -m rule --add app="^System Information$" manage=off
yabai -m rule --add app="^IINA$" manage=off
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^Finder$" title="^Copy$" manage=off
yabai -m rule --add app="^Harvest$" manage=off
yabai -m rule --add app="^Messages$" manage=off
yabai -m rule --add app="^Notes$" manage=off
yabai -m rule --add app="^Raycast$" manage=off
yabai -m rule --add app="^Hidden Bar$" manage=off
yabai -m rule --add app="^Brave Browser$" title="^(Untitled|My accounts) - Brave - 4k$" manage=off

echo "yabai configuration loaded..."
