# PHP
export PATH="$PATH:$HOME/.composer/vendor/bin"

# NVM
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# zsh-syntax-highlighting
source /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# zsh-autosuggestions
source /usr/local/share/zsh-autosuggestions/zsh-autosuggestions.zsh

# You may need to manually set your language environment
export LANG=en_US.UTF-8

export EDITOR='nvim'

[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# Starship
eval "$(starship init zsh)"

# BEGIN SNIPPET: Platform.sh CLI configuration
HOME=${HOME:-'/Users/andres'}
export PATH="$HOME/"'.platformsh/bin':"$PATH"
if [ -f "$HOME/"'.platformsh/shell-config.rc' ]; then . "$HOME/"'.platformsh/shell-config.rc'; fi # END SNIPPET

# exa.
alias ls='exa --color always --icons'
alias ll='exa --long --color always --icons'
alias la='exa --all --color always --icons'
alias lla='exa --long --all --color always'

#nvim.
alias v='nvim'

# bat.
alias cat=bat

# Enable vi mode (https://github.com/jeffreytse/zsh-vi-mode)
source $HOME/.zsh-vi-mode/zsh-vi-mode.plugin.zsh

# Rust.
source $HOME/.cargo/env

# The plugin will auto execute this zvm_after_init function
function zvm_after_init() {
  # fzf helpers.
  [ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
}

# fzf helpers.
# [ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# fzf configuration
export FZF_TMUX_OPTS='-p80%,60%'
export FZF_DEFAULT_COMMAND='rg --files --hidden'
export FZF_ALT_C_COMMAND='blsd'

# Remap Alt-C to Ctrl-G. 
bindkey -M viins '^g' fzf-cd-widget
# bindkey -M emacs '^g' fzf-cd-widget

# bindkey -M viins "^[[1;2C" forward-word
# bindkey -M viins "^[[1;2D" backward-word
# bindkey -M viins "^[b" backward-word     # ⌥←
# bindkey -M viins "^[f" forward-word      # ⌥→
# bindkey -M viins "^[[1;9D" beginning-of-line # cmd+←
# bindkey -M viins "^[[1;9C" end-of-line       # cmd+→
# bindkey -M emacs "^[b" backward-word     # ⌥←
# bindkey -M emacs "^[f" forward-word      # ⌥→

# Edit command line.
autoload -z edit-command-line
zle -N edit-command-line
bindkey "^X^E" edit-command-line

# Xoxide.
eval "$(zoxide init zsh)"

# Homebrew github api key.
source ~/.zshrc.local
